-- Tabela de usuarios do sistema.
create table usuario (
    id             bigint generated by default as identity,
    login          varchar(100) not null,
    nome_exibicao  varchar(150) not null,
    senha          varchar(255) not null,
    criado_em      timestamptz,
    criado_por     varchar(100),
    atualizado_em  timestamptz,
    atualizado_por varchar(100),
    constraint pk_usuario primary key (id),
    constraint uk_usuario_login unique (login)
);
